defaults:
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

device: cpu

n_epochs: 5
batch_size: 64
compress_dims:
  - 128
  - 100
embedding_dim: 16

dataset:
  name: janus
  root: ../data/fulldataset.csv
  n_classes_allowed: 2

training_config: configs/training_config.yaml

models:
  - src.pythae.models.VAE
  - src.pythae.models.VAMP
  - src.pythae.models.IWAE
  - src.pythae.models.VAE_LinNF
  - src.pythae.models.VAE_IAF
  - src.pythae.models.BetaVAE
  - src.pythae.models.DisentangledBetaVAE
  - src.pythae.models.BetaTCVAE
  - src.pythae.models.FactorVAE
  - src.pythae.models.INFOVAE_MMD
  - src.pythae.models.Adversarial_AE
  - src.pythae.models.MSSSIM_VAE
  - src.pythae.models.VAEGAN

model_configs:
  module:
    - src.pythae.models.VAEConfig
    - src.pythae.models.VAMPConfig
    - src.pythae.models.IWAEConfig
    - src.pythae.models.VAE_LinNF_Config
    - src.pythae.models.VAE_IAF_Config
    - src.pythae.models.BetaVAEConfig
    - src.pythae.models.DisentangledBetaVAEConfig
    - src.pythae.models.BetaTCVAEConfig
    - src.pythae.models.FactorVAEConfig
    - src.pythae.models.INFOVAE_MMD_Config
    - src.pythae.models.Adversarial_AE_Config
    - src.pythae.models.MSSSIM_VAE_Config
    - src.pythae.models.VAEGANConfig
  root:
    - configs/model_configs/vae_config.yaml
    - configs/model_configs/vamp_config.yaml
    - configs/model_configs/iwae_config.yaml
    - configs/model_configs/vae_lin_nf_config.yaml
    - configs/model_configs/vae_iaf_config.yaml
    - configs/model_configs/beta_vae_config.yaml
    - configs/model_configs/disentangled_beta_vae_config.yaml
    - configs/model_configs/beta_tc_vae_config.yaml
    - configs/model_configs/factor_vae_config.yaml
    - configs/model_configs/info_vae_config.yaml
    - configs/model_configs/aae_config.yaml
    - configs/model_configs/msssim_vae_config.yaml
    - configs/model_configs/vaegan_config.yaml
