defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null  
  run:  
    dir: .

seed: 42
dtype: float64

experiment_name: "mnist"
root: "examples/mnist/results"
save: true

digit: 3
normalize_targets: False

device: "cuda"

epochs: 100

train_batch_size: 32
train_shuffle: false
train_drop_last: false
pin_memory: true
num_workers: 0

valid: false
valid_batch_size: 32
valid_shuffle: false
valid_drop_last: false

add_scheduler: false
lr: 1e-3
weight_decay: 1e-5

weight_type: "rank"
rank_weight_k: 1e-3

p: 0.3
data_dim: 784
decompress_dims:
  - 128
  - 128

compress_dims:
  - 128
  - 128
embedding_dim: 2
bayesian: false


model:
  encoder:
    data_dim: ${data_dim}
    compress_dims: ${compress_dims}
    embedding_dim: ${embedding_dim}
    bayesian: ${bayesian}
  decoder:
    embedding_dim: ${embedding_dim}
    decompress_dims: ${decompress_dims}
    data_dim: ${data_dim}
    p: ${p}
    bayesian: ${bayesian}

beta_kld: 1.0
beta_reg: 1.0

optimization:
  optimize: false
  optimization_method: "bayesian_optimization"

  n_steps: 10
  gradient_scale: 10
  normalize_gradients: true
  
  no_uncertainty: false
  uncertainty_threshold_value: 10
  n_simulations: 100
  n_sampled_outcomes: 10

  save_history: true

  maximize: false

  lower_bound: 10
  upper_bound: 20

  pop_size: 300
  verbose: true
